name: Check for gpuCI updates

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-gpuci:
    runs-on: ubuntu-latest
    # if: github.repository == 'rapidsai/dask-build-environment'

    steps:
      - uses: actions/checkout@v2

      - name: Get old cuDF / UCX-Py versions
        run: |
          echo RAPIDS_VER=$(grep -A 2 "RAPIDS_VER" ci/axis/dask.yaml | tail -n1 | grep -o "'.*'" | sed "s/'//g") >> $GITHUB_ENV
          echo UCX_PY_VER=$(grep -m2 "UCX_PY_VER" ci/gpuci/run.sh | tail -n1 | grep -o '".*"' | sed 's/"//g') >> $GITHUB_ENV

      - name: Get latest cuDF nightly version
        id: cudf_latest
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "rapidsai-nightly"
          package: "cudf"
          version_system: "CalVer"

      - name: Get latest UCX-Py nightly version
        id: ucx_py_latest
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "rapidsai-nightly"
          package: "ucx-py"
          version_system: "SemVer"

      - name: Strip git tags from versions
        env:
          FULL_RAPIDS_VER: ${{ steps.cudf_latest.outputs.version }}
          FULL_UCX_PY_VER: ${{ steps.ucx_py_latest.outputs.version }}
        run: |
          echo "NEW_RAPIDS_VER=${FULL_RAPIDS_VER::-10}" >> $GITHUB_ENV
          echo "NEW_UCX_PY_VER=${FULL_UCX_PY_VER::-9}" >> $GITHUB_ENV

      - name: Update axis file
        uses: jacobtomlinson/gha-find-replace@0.1.4
        with:
          include: 'ci\/axis\/dask\.yaml'
          find: "RAPIDS_VER:\n  - .*\n  - .*"
          replace: |-
            RAPIDS_VER:
              - '${{ env.RAPIDS_VER }}'
              - '${{ env.NEW_RAPIDS_VER }}'

      - name: Update run file
        uses: jacobtomlinson/gha-find-replace@0.1.4
        with:
          include: 'ci\/gpuci\/run\.sh'
          find: "case(.|\n)*esac"
          replace: |-
            case ${{ '$RAPIDS_VER' }} in
              "${{ env.RAPIDS_VER }}")
                UCX_PY_VER="${{ env.UCX_PY_VER }}"
                ;;
              "${{ env.NEW_RAPIDS_VER }}")
                UCX_PY_VER="${{ env.NEW_UCX_PY_VER }}"
                ;;
              *)
                echo "Unrecognized RAPIDS_VER: ${{ '${RAPIDS_VER}' }}"
                exit 1
                ;;
            esac

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update gpuCI `RAPIDS_VER` to `${{ env.NEW_RAPIDS_VER }}`"
          title: "Update gpuCI `RAPIDS_VER` to `${{ env.NEW_RAPIDS_VER }}`"
          reviewers: "charlesbluca"
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: "upgrade-gpuci-rapids"
          body: |
            A new cuDF nightly version has been detected.

            Updated `dask.yaml` and `run.sh` to use `${{ env.NEW_RAPIDS_VER }}`.
